matrix:
  include:
    - language: java
      sudo: false # faster builds
      jdk:
        - oraclejdk11
      services:
        - mongodb
      env:
        global:
          - MONGODB_HOSTNAME=127.0.0.1
          - MONGODB_PORT=27017
          - MONGODB_DB=test
      script: mvn clean compile test
    - language: android
      jdk: oraclejdk8
      sudo: false

      env:
        global:
          # - ABI=x86_64
          - ADB_INSTALL_TIMEOUT=8
          - ANDROID_HOME=${HOME}/android-sdk

      android:
        components:
          - platform-tools
          - tools

          # The BuildTools version used by your project
          - build-tools-29.0.1

          # The SDK version used to compile your project
          - android-28
          - android-29

          # Additional components
          - extra-android-m2repository

          # Specify at least one system image,
          # if you need to run emulator(s) during your tests
          - sys-img-x86-android-29
          - sys-img-armeabi-v7a-android-29

      before_script:
        # Create and start emulator
        # - gradle wrapper
        - chmod +x ./hw12/gradlew
        # - echo no | android create avd --force -n test -t android-29 --abi armeabi-v7a
        # - emulator -avd test -no-audio -no-window &
        # - android-wait-for-emulator
        # - adb shell input keyevent 82 &

      script:
        - cd ./hw12 && ./gradlew build
        # - ./gradlew connectedAndroidTest
