matrix:
  include:
    - language: java
      sudo: false # faster builds
      jdk:
        - oraclejdk11
      services:
        - mongodb
      env:
        global:
          - MONGODB_HOSTNAME=127.0.0.1
          - MONGODB_PORT=27017
          - MONGODB_DB=test
      script: mvn clean compile test
    - language: android
      jdk: oraclejdk8
      sudo: false

      android:
        components:
          - platform-tools
          - tools
          - build-tools-29.0.1
          - android-28
          - android-29
          - sys-img-armeabi-v7a-android-29
          - extra-android-m2repository

      before_script:
        # Create and start emulator
        - echo no | android create avd --force -n test -t android-29 --abi armeabi-v7a
        - emulator -avd test -no-skin -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &

      script: ./gradlew connectedAndroidTest
